const julesStories = [
  `     It was a hot day towards the end of fifth grade when I suddenly turned off from my typical route home. My bookbag repeatedly thumped against my back as the bicycle rumbled down the uneven dirt road, approaching the abandoned home I’d heard whispers about in school. After stopping in the lot’s front yard I leaned my belongings against the wide trunk of an old oak tree. A simple wood plank swing hung from its sturdiest branch. When I sat on it my toes dangled just above the blades of overgrown grass. I dug around my pockets for my IPod and opened my “Ballroom” playlist. “Sing, Sing, Sing” came on- the song our dance instructor used to teach us the swing. The fitting coincidence brought a brief smile to my face as I pumped my legs to pick up momentum on the actual swing. 

     I closed my eyes to imagine practicing my steps. I had it down, every triple step and turn. I pushed my legs out and swung even higher. As my stomach lurched I realized I was imagining the wrong role, the lead. The fuzzy image of my own shorter form entered my mind’s eye. I watched myself stumble as the boy pulled me along. My eyes shot open, the view of the blue sky and leafy oak branches chasing away the unpleasant image. I reached higher on each rope and pulled myself up, standing upright on the seat of the swing. With a deep breath I shut my eyes again, hoping to see the dance through to the end. This time I was on the stage with the rest of the grade, and as my partner spun me I saw the magenta skirt Mom bought for the occasion flare out around me. And this time, my eyes were forced open by the sudden feeling of air beneath my feet, which had fully slipped from the plank.`,
  `     That accident broke my arm. I thought it would be devastating to miss out on so much, like the ballroom dance show and Twelfth Night production preceding our graduation ceremony. After all, I’d been cast as the fairy queen Tatiana, a role that all the other girls in my class coveted. I had diligently memorized my lines outside of class time, determined to prove I was the right choice. Everyone knew I loved dance, so I had to master the ballroom routines as well- hence the playlist I often listened to on repeat. In the end all my effort amounted to nothing, and at first I was just as frustrated as Mom.

	     I sat in the audience of the auditorium during dance and theater class, watching my peers rehearse. The new Tatiana looked so graceful as she skipped onto stage in her glittering wings. But strangely, I didn’t feel all that bitter or disappointed. Instead, I settled into strange and private peace. As skirts twirled and familiar ballroom tracks played I felt every expectation, every role that clung to my skin and tangled in my hair shed away. 
	
       Once my cast was removed, I often found myself returning to the swing I had fallen from. With the wind rushing past me and the sky closer than ever, I could almost relive that fleeting contentment. 
`,
  `     As a teen I gradually discarded every personal item that felt like a mask: butterfly wall decals, colorful clothes, my old glitter-covered backpack. It was fine until that Easter Sunday, when Mom realized I had no dress to wear to my grandparents’ place. I think that was when it clicked for her: this wasn’t the typical phase of a teen trying to mature too fast.
     Mom was silent as she drove us to Macy’s. Once inside, I was overwhelmed by frigid AC’d air that stank of floral soap and the vice-like grip Mom held on my wrist while pulling me through the store. There wasn’t a sound between us, only the feel-good pop songs that blared from all directions as Mom led us to the women’s section. She stopped in front of the very first rack and took a random dress, pushing it to my chest with enough force to feel like a punch. I held onto it quickly, as if it were the reins of a spooked horse. But it gave me no power to steer as Mom ushered me into a changing room. Finally having a moment to myself, I looked over the dress and noticed just how awful it really was. I called out to Mom, telling her how the colors didn’t look right for me, and it might be a size too big. “Put it on.” She spat back, sounding closer to the other side of the door than I expected. I tried to open the door to show her, but the handle wouldn’t budge. My stomach lurched and my heart began to hammer in my chest. “I said put it on.” Mom repeated while holding the changing room door shut from outside.
     The family photo taken that day was framed and hung in the entry hallway of the house. In it, I stood off to the side as if trying to avoid the camera, but my awkward distance from the group only brought more attention to the ill-fitting sundress cluttered with garish floral patterns. My short hair failed to hide the sales tag that poked out from my neckline. That became the last printed picture of me displayed at home. 
`,
  `The day after that terrible Easter, I had geometry class first period. I laid my head down on my desk, It wasn’t as if I’d be participating anyway. Besides, I actually performed well in that course when it came to assignments and exams, so one period of slacking should’ve been excusable. As soon as my cheek touched the cool surface of my desk, I heard the stern stride of Mr.Acker approach. He began to yammer in my ear with more passion than he ever spared any of his lessons. Even when I promised to still pay attention, or that it would be just for today- just one period of ease, he doubled down, taking further offence at my attempt to negotiate. 
It hit me then: he had been waiting for this moment. I recalled how I was always cold called more than the other quiet students, and how Mr.Acker spent the majority of test periods hovering around my desk. Now that I’d finally given him something to call “misbehavior”, he wouldn’t let it go. I shot up from my seat, and faced him eye to eye before pushing past him, intending to leave the room. Something suddenly jerked me back, and I spun around to find the hood of my sweatshirt clenched tight in his knobby knuckles. Before I could form a full thought, my own clenched fist went hurtling towards the sickening smirk on his face. 
	Following that incident, my life at high school became just as suffocating as my life at home. Suddenly everyone had a reason to feel justified in making me a target. Perhaps due to my immaturity, I figured I might as well do at school what I couldn’t do at home: act out. Every time I responded to a teacher’s provocation by yelling, shutting down, or storming out, I was foolishly pouring myself into the mold they had created.
`,
  `My hand shook as I tried the key, it had been half a year since I dropped out of high school and got kicked out of home. To my relief, the sound of a click confirmed they hadn’t changed the locks. Even though I chose a time both Mom and Dad would be out of the house, a chill of unease seized me as soon as I stepped inside. After couch surfing and living out of my backpack for months, I finally found a stable enough serving job to split rent with a few roommates. As nice as it was to be able to settle in, I had dreaded returning to my parents’ house for my things. 
My room was just as I had left it- a complete mess. I set the rolling suitcase my roommate Sam lent me on my unmade bed and began to pack. It hadn’t been all that long since the days that I’d come home, lock myself in my room, and amp up my minispeaker to its limit. Yet looking at it now felt strangely distant, as if it had been years since I was that helpless wild teen.
I was almost shocked by my own collection of excess: half-full journals with more doodles than notes, piles of redundant clothes, peeling band posters, random trinkets I had assigned some sentimental value. Living lightly made me realize how little I really needed. I folded up a few plain, work-appropriate shirts. My favorite graphic tee- featuring a cartoon rave couple ballroom dancing- called to me. I nearly placed it in the suitcase before I came to my senses and tossed it aside. I had no need for that kind of cope anymore.
I was about to leave the room before I glanced over my shoulder to give it one last look. I didn’t think or hesitate when I let go of the suitcase and rolled up my sleeves. I just started tidying up like it was the natural thing to do. I didn’t listen to any music or set a timer like I usually would while cleaning. I simply worked silently- my hands moving on their own to organize my desk, straighten up posters, and put away clothes. The last thing I did was fluff the pillow on my made up bed. Satisfied, I clicked the light switch off and left without looking back. The suitcase I pulled glided on the hardwood floors with the same pace and rumble as when I entered. But as I dragged it behind me I could feel the subtly increased weight from my belongings.
`,
  `Working as a receptionist at a hotel with Sam was one of the easier jobs I had. Though we didn’t live together anymore, Sam pulled some strings to get me even working the same shift as him. We must have made quite the sight: sitting side by side with our bound chests, short hair, and ambiguous hormone-altered voices asking “How can I help you today?” 
           Sam knew how to take full advantage of the position. He would bring in his drawing tablet and connect it to the desktop, flipping from his illustration to the guest registration window whenever a customer or higher up walked by. He always offered me a chance to try it out, and one day I gave in.
       It was a slow weekday, I’d barely seen anyone even pass by on the street for the first two hours of our late night shift. I picked up the pen and made a few strokes on the tablet, watching how they dashed across the desktop screen. One button could completely undo a drawn line, as if it was never there to begin with. It was completely different from the feel of a #2 pencil on composition notebook paper, and the pink eraser that could never fully scrub away a smudge of graphite. I slipped an earbud into one ear and let random songs from my favorites list play while I made all sorts of shapes, colors, and textures flash onto and off of the screen. 
     “You know you can save your work and just open a new canvas for a blank page.” Sam sighed. “At this point you’re not drawing, you’re dancing.”
     I smiled and shrugged, then froze as I saw his expression crumble into dread. I clumsily switched to a new window, but it was too late. When I turned around, our manager asked to speak to us both, individually. 
       I kept my mouth shut and a week later I was fired. A few days afterwards, I received a gift in the mail from Sam: a new drawing tablet, just for me. It came with a note in which he admitted that he threw me under the bus, falsely assuming that I would do the same.
`,
  `With nothing left to stay for, I took myself, my savings, one suitcase of belongings, and a backpack on a one-way flight to California. My first stop was an RV dealership, where an overzealous salesman led me around the baking hot lot. He proudly presented the latest top models of Class A and C motorhomes. I was impressed by the sleek storage, private bedrooms, high-tech kitchenettes, rain showers, and skylights, until they were followed up by a fair but enormous price.
The next price bracket took me to the older models of towable trailers with classic furnishings and warm beige color pallets. Unfortunately, the cost was still a bit startling. My salesman grew reluctant, but I insisted on seeing the true deals. In a shady corner towards the back of the lot there were a few options well within my budget: used campervans. Some looked like they came straight from a demolition derby, and none of them were particularly roomy. But like fate, a humble baby blue beauty sporting only a few scratches caught my eye. She was compact- a skinny bed took up most of the space between the kitchenette and bathroom, which did not include a shower. A single fish-patterned curtain in front of the toilet was the most privacy the vehicle offered. 
I named her Skylark, Sky for short. The tablet I refused to touch out of bitterness, but brought along anyway, finally became of use. With it, I designed an emblem of a bird swooping around the sun, and had it painted over the most noticeable scratch. 
With that, my grudge was dissolved and something within me was opened up. I began to draw everyday, even posting some of my pieces: fanart from the latest popular franchise, comic strips about whatever odd job I worked, and portraits of the people I met. Through different commissions and side projects I earned some bonus income for myself. It wasn’t much, but it was enough to supplement my travel funds as needed. 
`,
  `A few years into retirement I suddenly awoke with a hollowing loneliness. I got to work making phone calls and sending out letters, emails, and texts. The time had finally come for me to hit the road again. It was my most extensively planned trip across the country, designed for the purpose of visiting anyone and everyone I knew. There were plenty of people I’d met on the road in my nomadic phases, and others I befriended in the various places I tried to settle down in.
         My last stop was with Tina and Mark, a couple I had met rather early on in my journey. I was worried it had been too long to reunite comfortably, but despite changing over the years, we got on like old friends.
We met on the beach as the sun set. I folded out the tarp extension from the side of my van and they brought foldable chairs to prop up in the sand underneath. We reclined with a sigh and got to talking, passing around Pinot and dried dates. At some point Tina clapped her hands and pointed at my van.
“Oh! We need to show you! After we first met you, Mark and I loved that design so much that we just had to ink it.” 
I’d long since upgraded from Skylark, but I kept the emblem on every vehicle I owned. The heavily tattooed couple each held out an arm, and sure enough, that swooping bird sat just below their wrists. Any lingering regret over never putting down roots was carried away by my delighted laughter.
The two got up and swayed in each other's arms to the rhythm of the lapping waves and crackling bonfire. I retrieved a pen and took out my travel sketchbook, opening to one of the last remaining blank pages.
`,
  `TODO`,
]

const adonisStories = [``, ``, ``, ``, ``, ``, ``, ``, ``]
const miaStories = [``, ``, ``, ``, ``, ``, ``, ``, ``]
const kitzStories = [``, ``, ``, ``, ``, ``, ``, ``, ``]
const imaniStories = [``, ``, ``, ``, ``, ``, ``, ``, ``]
const mitraStories = [``, ``, ``, ``, ``, ``, ``, ``, ``]

export default [
  julesStories,
  adonisStories,
  miaStories,
  kitzStories,
  imaniStories,
  mitraStories,
]
