import Catalog from '../../../../shared/state/catalog'

// TODO Split into files

// Helper function to create arrays of card IDs
const x = (cardName: string, count: number): number[] => {
  const card = Catalog.getCard(cardName)

  if (card === undefined) {
    console.log(`When making a journey mission, card ${cardName} not found`)
  }

  return card ? Array(count).fill(card.id) : []
}

export type JourneyMission = {
  selectText: string
  missionText: string
  uponRoundWinText: [string, string, string, string, string, string]
  deck: number[]
  opponentDeck: number[]
  winText: string
  loseText: string
}

export type JourneyMissionTracks = JourneyMission[][]

export const JOURNEY_MISSIONS: JourneyMissionTracks = [
  // Jules
  [
    {
      selectText: `It's nice to meet you.`,
      missionText: `It’s a pleasure to meet you, [player name?]. I hope you’re not feeling too disoriented. If you’d like, I could show you around this [term for neighborhood]. But if you do join me, you’ll have to lend me your ear while I reminisce a little. The great tree in this courtyard reminds me of a place of respite in my youth…`,
      uponRoundWinText: [
        `I won't stop until I know the truth.`,
        '1',
        '2 Oh, maybe that is the truth.',
        '3 Nope, not that...',
        '4 Hrmmmm :/',
        '5 Wait, I got it!',
      ],
      deck: [
        ...x('Stars', 2),
        ...x('Dove', 5),
        ...x('Starling', 3),
        ...x('Mercy', 2),
        ...x('Hurricane', 1),
        ...x('Uprising', 2),
      ],
      opponentDeck: [3, 3, 3, 3, 3, 3, 6, 6, 6, 6, 11, 11, 14, 14, 17],
      winText: 'Thanks for your help.',
      loseText: 'Oh well, maybe next time.',
    },
    {
      selectText: `I used to dance, before the accident.`,
      missionText: `Isn’t the landscaping here just beautiful? It’s all the work of the Umbra. They get inspired from all that they hear and shape their surroundings accordingly. I think there is peace to be found in the everchanging. I used to be too afraid, too troubled to see that.`,
      uponRoundWinText: [
        `The blank canvas remains...`,
        `Maybe there's something worth painting.`,
        `I can see a faint outline forming.`,
        `The colors aren't so repulsive anymore.`,
        `I think I'm ready to start.`,
        `The canvas is calling to me.`,
      ],
      deck: [
        ...x('Dove', 6),
        ...x('Starling', 3),
        ...x('Mercy', 2),
        ...x('Sun', 1),
      ],
      opponentDeck: [3, 3, 3, 3, 3, 3, 6, 6, 6, 6, 11, 11, 14, 14, 17],
      winText: 'The little voice was right. I got through this.',
      loseText: 'The blank canvas is still there, waiting.',
    },
    {
      selectText: `Dresses aren't really my thing.`,
      missionText: `You’ve adjusted so quickly, [player name]! You know, I think you’re a rather interesting Umbra. There is something refreshing about telling stories with you. It makes me want to reveal parts of myself I’ve kept under wraps. There was a time when my routine of keeping my head down and shutting up began to break apart…`,
      uponRoundWinText: [
        `The old routine is breaking apart.`,
        `I can't keep my head down anymore.`,
        `The tears are coming, and that's okay.`,
        `I'm not out of control - I'm breaking free.`,
        `The light is getting brighter.`,
        `I am Jules, and I am reborn.`,
      ],
      deck: [...x('Dove', 6), ...x('Heron', 2), ...x('Starling', 3)],
      opponentDeck: [3, 3, 3, 3, 3, 3, 6, 6, 6, 6, 11, 11, 14, 14, 17],
      winText: 'I am Jules, and I am light.',
      loseText: 'The rebirth is still happening, even in loss.',
    },
    {
      selectText: `It felt right to leave home.`,
      missionText: `hmmmm some writing goes here....`,
      uponRoundWinText: [
        `I am Jules, no reservations.`,
        `Each place teaches me something new.`,
        `The colors are beautiful everywhere.`,
        `I don't need to hold onto anything.`,
        `Freedom feels like this.`,
        `I am Jules, and I am free.`,
      ],
      deck: [
        ...x('Stars', 2),
        ...x('Dove', 5),
        ...x('Cosmos', 1),
        ...x('Phoenix', 2),
      ],
      opponentDeck: [21, 51, 51, 14, 14, 11, 11, 6, 7, 7, 3, 3, 4, 4, 5],
      winText: 'I am Jules, and I have found peace.',
      loseText: "The journey continues, and that's okay.",
    },
    {
      selectText: `Want to see what I've been sketching?`,
      missionText: `Sometimes the light is so bright it hurts. But that's how you know it's real.`,
      uponRoundWinText: [
        `The sun is rising.`,
        `I can feel its warmth.`,
        `The light is almost too bright.`,
        `But I won't look away.`,
        `I am becoming the light.`,
        `I am the sun.`,
      ],

      deck: [...x('Dove', 5), ...x('Heron', 2), ...x('Vulture', 3)],
      opponentDeck: [21, 20, 20, 17, 14, 14, 14, 6, 3, 3, 3, 3, 0, 0, 0],
      winText: 'I am the sun, and I shine.',
      loseText: 'Even the sun sets, but it always rises again.',
    },
    {
      selectText: `Drawing saved me when I had lost everything.`,
      missionText: `The morning dew catches the light in ways that make everything new again.`,
      uponRoundWinText: [
        `Fresh as morning dew.`,
        `Each drop reflects the light.`,
        `Everything feels renewed.`,
        `The world is sparkling.`,
        `I am refreshed.`,
        `I am the morning dew.`,
      ],
      deck: [21, 20, 51, 63, 63],
      opponentDeck: [12, 12, 12, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
      winText: 'I am the morning dew, pure and fresh.',
      loseText: 'The dew will return with the next morning.',
    },
    {
      selectText: `Bought a van and hit the road alone.`,
      missionText: `Sometimes you have to fight for what you believe in, even when the odds are against you.`,
      uponRoundWinText: [
        `I will not back down.`,
        `The fight is worth it.`,
        `I am stronger than I look.`,
        `My spirit cannot be broken.`,
        `I am ready for anything.`,
        `I am the gamecock.`,
      ],
      deck: [51, 40, 40, 32, 63, 1, 3],
      opponentDeck: [12, 12, 12, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
      winText: 'I am the gamecock, and I have won.',
      loseText: 'The gamecock never gives up, even in defeat.',
    },
    {
      selectText: `Getting older, but still feel that freedom.`,
      missionText: `Everything is connected. Every choice affects the whole. I am part of something bigger than myself.`,
      uponRoundWinText: [
        `I am connected to everything.`,
        `My choices matter.`,
        `I am part of the whole.`,
        `The web of life supports me.`,
        `I am in harmony.`,
        `I am ecology.`,
      ],
      deck: [56, 71, 71, 69, 69],
      opponentDeck: [12, 12, 12, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
      winText: 'I am ecology, and I am in balance.',
      loseText: 'The ecosystem continues, with or without me.',
    },
    // More levels
  ],
  // Adonis
  [
    {
      selectText: `You can tag along if you want.`,
      missionText: `So, you say you’re here to help me… I don’t know if that’s possible. I’m gonna be checking in on some projects around the [name for neighborhood], and the Umbras will bug me for my story again. I guess you could try your thing, I won’t stop you. Before we start, you should know my family struggled from day one…`,
      uponRoundWinText: [
        `Fire begins`,
        ``,
        `22222`,
        `33`,
        `4`,
        `5 let's go bay-beeeee`,
      ],
      deck: [
        ...x('Stars', 3),
        ...x('Impulse', 5),
        ...x('Dash', 2),
        ...x('Fruit', 1),
        ...x('Mercy', 2),
        ...x('Veteran', 2),
      ],
      opponentDeck: [11, 11, 11, 11, 7, 7, 7, 4, 4, 4, 4, 4, 4, 0, 0],
      winText: 'Adonis win text heehee',
      loseText: 'Adonis lose text heehee',
    },
    {
      selectText: `You coming? I've got work to do.`,
      missionText: `Not bad, [player name]. I promised to tell some Umbra down by the bonfire about my first love, want to join us? I could use your help. You see, I was desperate for opportunity as soon as I could work. People often told me to slow down, but I knew I still wasn’t fast enough. Some understood that better than others. `,
      uponRoundWinText: [
        `The spark ignites.`,
        `The fire grows stronger.`,
        `I can feel the heat building.`,
        `The flames dance higher.`,
        `The inferno rages.`,
        `I am the fire.`,
      ],

      deck: [
        ...x('Stars', 2),
        ...x('Impulse', 5),
        ...x('Arsonist', 2),
        ...x('Veteran', 2),
      ],
      opponentDeck: [5, 5, 5, 3, 3, 3, 6, 12, 14, 14, 13, 13, 17, 17, 17],
      winText: 'The fire consumes all.',
      loseText: 'The spark still smolders.',
    },
    {
      selectText: `I take care of my siblings - it's what I do.`,
      missionText: `This next part is always the hardest to retell. At least I have you here with me this time. Mom babysat all over the city, sometimes even overnight, and Dad took a bus out to the edge of the suburbs to work 12 hour shifts at a factory. Knowing that, I shouldn’t have taken the downtown job that kept me out until the late evening…`,
      uponRoundWinText: [
        `The inferno rages on.`,
        `Death walks with me.`,
        `Everything turns to ash.`,
        `The destruction is complete.`,
        `I am the bringer of death.`,
        `From ashes, new life will grow.`,
      ],

      deck: [
        ...x('Impulse', 5),
        ...x('Arsonist', 2),
        ...x('Veteran', 2),
        ...x('Death', 1),
      ],
      opponentDeck: [56, 51, 51, 11, 12, 7, 7, 7, 4, 4, 4, 4, 4, 0, 0],
      winText: 'Death has claimed another.',
      loseText: 'The fire still burns within.',
    },
    {
      selectText: `Had to grow up fast after we lost Kierra.`,
      missionText: `Even in the aftermath, something clings to life. The fire may have burned everything to the ground, but from the ashes, new possibilities emerge.`,
      uponRoundWinText: [
        `Something survives the flames.`,
        `Life clings to existence.`,
        `From destruction comes renewal.`,
        `The cycle continues.`,
        `I cling to hope.`,
        `From ashes, I rise.`,
      ],

      deck: [
        ...x('Stars', 2),
        ...x('Arsonist', 3),
        ...x('Cling', 2),
        ...x('Death', 1),
      ],
      opponentDeck: [56, 51, 51, 11, 12, 7, 7, 7, 4, 4, 4, 4, 4, 0, 0],
      winText: 'I cling to life and victory.',
      loseText: 'The ashes still hold potential.',
    },
    {
      selectText: `Got hurt overseas, but I made it back.`,
      missionText: `Sometimes the fire meets water, and everything drowns in the conflict. The heat and the cold battle for dominance, and I am caught in the middle.`,
      uponRoundWinText: [
        `The fire meets water.`,
        `Steam rises from the conflict.`,
        `I am drowning in the heat.`,
        `The battle rages on.`,
        `I am submerged in chaos.`,
        `I will not drown.`,
      ],

      deck: [
        ...x('Impulse', 4),
        ...x('Mine', 2),
        ...x('Cling', 2),
        ...x('Death', 1),
      ],
      opponentDeck: [56, 65, 65, 51, 12, 12, 7, 7, 7, 4, 4, 4, 4, 4, 4],
      winText: 'I have conquered the depths.',
      loseText: 'The water has claimed me.',
    },
    {
      selectText: `I'm trying to make things right with old friends.`,
      missionText: `What is mine, I will defend. What I have lost, I will reclaim. The fire has taken much from me, but I will take back what belongs to me.`,
      uponRoundWinText: [
        `This is mine.`,
        `I will not let go.`,
        `I reclaim what was taken.`,
        `My territory is secure.`,
        `I defend what is mine.`,
        `I am the master of my domain.`,
      ],
      deck: [15, 15, 3, 3, 0, 0],
      opponentDeck: [12, 12, 12, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
      winText: 'What is mine remains mine.',
      loseText: 'I have lost my claim.',
    },
    {
      selectText: `Visit my sister's grave when I need to remember.`,
      missionText: `The fire has left everything parched and dry. The land thirsts for water, but I have learned to thrive in the heat. I am the drought, I am the thirst.`,
      uponRoundWinText: [
        `The land is parched.`,
        `I am the drought.`,
        `Everything thirsts for relief.`,
        `I bring the heat.`,
        `The dryness is complete.`,
        `I am the parched earth.`,
      ],
      deck: [21, 68, 68, 64, 64],
      opponentDeck: [12, 12, 12, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
      winText: 'I have parched the land.',
      loseText: 'The drought continues.',
    },
    {
      selectText: `Want to build something that helps everyone.`,
      missionText: `From the ashes of destruction, new life emerges. The cycle of death and rebirth continues. I have burned everything down, but now I will help it grow back stronger.`,
      uponRoundWinText: [
        `New life emerges.`,
        `The cycle continues.`,
        `From destruction comes growth.`,
        `I nurture the new.`,
        `The rebirth is complete.`,
        `I am the gardener of ashes.`,
      ],
      deck: [34, 74, 74, 3, 3, 3],
      opponentDeck: [12, 12, 12, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
      winText: 'From ashes, new life has sprouted.',
      loseText: 'The seeds still wait in the ashes.',
    },
    // More levels
  ],
  // Mia
  [
    {
      selectText: `Shadow 1 - The Dagger`,
      missionText: `gotta go shadow or something`,
      uponRoundWinText: [
        `0 I am afraid of the dark`,
        `1 I am not afraid of the dark`,
        `2 I am not afraid of the dark`,
        `3 I am not afraid of the dark`,
        `4 I am not afraid of the dark`,
        `5 I am not afraid of the dark`,
      ],
      deck: [
        ...x('Dagger', 4),
        ...x('Dash', 1),
        ...x('Fruit', 2),
        ...x('Hurricane', 1),
        ...x('Shadow', 3),
        ...x('Uprising', 1),
      ],
      opponentDeck: [18, 18, 51, 51, 15, 15, 48, 48, 48, 7, 7, 33, 33, 4, 4],
      winText: 'You are a true shadow.',
      loseText: 'I lost oh nooooo',
    },
    {
      selectText: `Shadow 2 - Hungy Mungy`,
      missionText: `The shadows hold secrets, and sometimes they hold weapons. I've learned to navigate the darkness, to find the sharp edges that others miss. The dagger is my companion in the night.`,
      uponRoundWinText: [
        `The shadows whisper secrets.`,
        `I find the sharp edges.`,
        `The dagger guides my hand.`,
        `I am one with the darkness.`,
        `The shadows protect me.`,
        `I am the shadow's blade.`,
      ],
      deck: [
        ...x('Dagger', 3),
        ...x('Hungry Ghost', 2),
        ...x('Fruit', 1),
        ...x('Hurricane', 1),
        ...x('Shadow', 2),
      ],
      opponentDeck: [21, 17, 17, 14, 14, 14, 12, 12, 6, 3, 3, 3, 3, 3, 0],
      winText: 'The shadows have spoken.',
      loseText: 'The darkness still calls.',
    },
    {
      selectText: `Victim`,
      missionText: `Nightmares are just shadows given form. I've learned to face them, to understand that fear is just another tool. The darkness can be terrifying, but it can also be a weapon.`,
      uponRoundWinText: [
        `The nightmare takes shape.`,
        `I face my fears head on.`,
        `The darkness becomes my ally.`,
        `I am not afraid anymore.`,
        `The nightmare serves me.`,
        `I am the nightmare.`,
      ],
      deck: [
        ...x('Dagger', 2),
        ...x('Victim', 2),
        ...x('Hungry Ghost', 2),
        ...x('Hurricane', 1),
        ...x('Shadow', 1),
      ],
      opponentDeck: [56, 56, 57, 57, 51, 51, 14, 11, 11, 11, 6, 1, 1, 1, 1],
      winText: 'I have conquered the nightmare.',
      loseText: 'The nightmare still lingers.',
    },
    {
      selectText: `Shadow 3 - The Imprisonment`,
      missionText: `Sometimes the shadows become a prison, trapping us in our own darkness. But I've learned that every prison has a key, and sometimes the key is understanding that the shadows are part of who I am.`,
      uponRoundWinText: [
        `The shadows close in.`,
        `I am trapped in darkness.`,
        `But I know the way out.`,
        `The prison cannot hold me.`,
        `I break free from the shadows.`,
        `I am free in the darkness.`,
      ],
      deck: [1, 1, 1, 1, 35, 35],
      opponentDeck: [18, 18, 15, 15, 48, 48, 12, 12, 6, 6, 3, 3, 3, 0, 0],
      winText: 'I have escaped the shadows.',
      loseText: 'The shadows still surround me.',
    },
    {
      selectText: `Bonus: Wing Clipping`,
      missionText: `Sometimes you have to clip your own wings to survive in the shadows. The light can be blinding, and sometimes it's better to stay grounded in the darkness where I can see clearly.`,
      uponRoundWinText: [
        `I clip my own wings.`,
        `I stay grounded in darkness.`,
        `The shadows protect me.`,
        `I am free from the light.`,
        `I choose the darkness.`,
        `I am the grounded shadow.`,
      ],
      deck: [20, 19, 19, 19, 16, 16, 1, 1],
      opponentDeck: [46, 57, 14, 11, 11, 11, 8, 8, 31, 31, 3, 3, 3, 2, 2],
      winText: 'I am free in my grounded state.',
      loseText: 'The shadows still call me down.',
    },
    {
      selectText: `Bonus: Hungry Ghost`,
      missionText: `The shadows are hungry, always wanting more. I've learned to feed them, to understand their hunger. Sometimes the darkness consumes, but I've learned to consume it back.`,
      uponRoundWinText: [
        `The shadows hunger.`,
        `I feed them my fear.`,
        `The darkness consumes.`,
        `But I consume it back.`,
        `I am the hungry shadow.`,
        `I am the ghost in the night.`,
      ],
      deck: [13, 13, 11, 68, 31, 31, 31, 1, 1, 0, 0],
      opponentDeck: [23, 57, 65, 51, 51, 11, 11, 69, 7, 7, 4, 4, 4, 4, 4],
      winText: 'I have fed the hungry shadows.',
      loseText: 'The shadows still hunger.',
    },
    {
      selectText: `Bonus: Sickness`,
      missionText: `The shadows can make you sick, but I've learned that sickness can also be a teacher. Sometimes the darkness shows you things that the light cannot. I embrace the sickness of the shadows.`,
      uponRoundWinText: [
        `The shadows make me sick.`,
        `But sickness teaches me.`,
        `I learn from the darkness.`,
        `The shadows reveal truth.`,
        `I am sick with knowledge.`,
        `I am the shadow's illness.`,
      ],
      deck: [65, 65, 58, 58, 7, 4, 4, 4],
      opponentDeck: [23, 20, 20, 19, 19, 17, 17, 11, 12, 7, 7, 5, 5, 5, 5],
      winText: 'I have learned from the sickness.',
      loseText: 'The shadows still make me ill.',
    },
    {
      selectText: `Bonus: Boa`,
      missionText: `The shadows coil around me like a boa, constricting and suffocating. But I've learned to breathe in the darkness, to find strength in the constriction. The shadows are my embrace.`,
      uponRoundWinText: [
        `The shadows coil around me.`,
        `I feel the constriction.`,
        `But I learn to breathe.`,
        `The darkness embraces me.`,
        `I find strength in suffocation.`,
        `I am the shadow's boa.`,
      ],
      deck: [20, 19, 57, 71],
      opponentDeck: [23, 57, 65, 51, 51, 11, 11, 69, 7, 7, 4, 4, 4, 4, 4],
      winText: "I have embraced the shadow's constriction.",
      loseText: 'The shadows still coil around me.',
    },
    // More levels
  ],
  // Kitz
  [
    {
      selectText: `I am a cat`,
      missionText: `I am a cat and this is my mission`,
      uponRoundWinText: [
        `0 I am afraid of the cat`,
        `1 I am not afraid of the cat`,
        `2 I am not afraid of the cat`,
        `3 I am not afraid of the cat`,
        `4 I am not afraid of the cat`,
        `5 I am not afraid of the cat`,
      ],
      deck: [11, 11, 11, 34, 34, 33, 33, 33, 4, 0, 0, 0],
      opponentDeck: [21, 20, 19, 19, 19, 17, 14, 12, 6, 6, 63, 63, 5, 5, 5],
      winText: 'I have won.',
      loseText: 'I lost :/',
    },
    {
      selectText: `Pet 1 - The Companion`,
      missionText: `Every cat needs a companion, someone to hold tight to in the darkness. I've learned that even the most independent creatures need connection. The pet becomes part of the family.`,
      uponRoundWinText: [
        `I find my companion.`,
        `We hold tight to each other.`,
        `The bond grows stronger.`,
        `We are family now.`,
        `I am not alone anymore.`,
        `I am the pet's guardian.`,
      ],
      deck: [
        ...x('Stars', 3),
        ...x('Cosmos', 1),
        ...x('Hold Tight', 1),
        ...x('Pet', 1),
        ...x('Fruit', 2),
        ...x('Uprising', 1),
        ...x('Oak', 1),
      ],
      opponentDeck: [23, 20, 19, 19, 19, 57, 51, 11, 11, 11, 6, 6, 63, 63, 0],
      winText: 'My companion and I are victorious.',
      loseText: 'The bond still holds us together.',
    },
    {
      selectText: `Rose time`,
      missionText: `Like an oak tree, I must be strong and steady for those who depend on me. The pet needs shelter, and I provide it. We grow together, becoming stronger with each passing day.`,
      uponRoundWinText: [
        `I stand strong like an oak.`,
        `I provide shelter and safety.`,
        `We grow together.`,
        `The roots run deep.`,
        `I am unshakeable.`,
        `I am the oak for my pet.`,
      ],

      deck: [
        ...x('Rose', 3),
        ...x('Hold Tight', 1),
        ...x('Pet', 2),
        ...x('Mercy', 2),
        ...x('Oak', 1),
      ],
      opponentDeck: [23, 46, 51, 15, 40, 12, 9, 6, 7, 7, 63, 63, 63, 63, 0],
      winText: 'The oak stands tall and proud.',
      loseText: 'The oak still provides shelter.',
    },
    {
      selectText: `Sunflower time`,
      missionText: `Sometimes the gentlest touch is the most powerful. Like gentle rain nurturing the earth, I nurture my companion with patience and care. The softest approach often works best.`,
      uponRoundWinText: [
        `The gentle rain falls.`,
        `I nurture with patience.`,
        `Soft touches heal.`,
        `Gentleness is strength.`,
        `The rain brings growth.`,
        `I am the gentle rain.`,
      ],
      deck: [
        ...x('Rose', 2),
        ...x('Sunflower', 2),
        ...x('Fruit', 2),
        ...x('Uprising', 1),
        ...x('Oak', 1),
      ],
      opponentDeck: [21, 17, 17, 14, 68, 68, 6, 31, 31, 3, 3, 3, 3, 3, 76],
      winText: 'Gentle rain has nurtured us to victory.',
      loseText: 'The gentle rain still falls.',
    },
    {
      selectText: `Hollow baybeeeee`,
      missionText: `I am hollow and this is my mission`,
      uponRoundWinText: [
        `The bounty is plentiful.`,
        `We share the spoils.`,
        `Together we prosper.`,
        `The hunt is successful.`,
        `We are well-fed.`,
        `I am the bounty hunter.`,
      ],
      deck: [...x('Hollow', 2)],
      opponentDeck: [21, 20, 20, 17, 14, 14, 14, 6, 3, 3, 3, 3, 0, 0, 0],
      winText: 'The bounty is ours to share.',
      loseText: 'The bounty still awaits us.',
    },
    {
      selectText: `Yearning`,
      missionText: `Sometimes the hollow places in our hearts can be filled by the love of a companion. The emptiness becomes a space for connection, for warmth, for belonging.`,
      uponRoundWinText: [
        `The hollow space calls.`,
        `I fill it with love.`,
        `The emptiness becomes warmth.`,
        `I am no longer hollow.`,
        `The space is filled.`,
        `I am whole with my companion.`,
      ],
      deck: [
        ...x('Stars', 1),
        ...x('Yearn', 4),
        ...x('Pet', 1),
        ...x('Fruit', 2),
      ],
      opponentDeck: [21, 20, 20, 17, 14, 14, 14, 6, 3, 3, 3, 3, 0, 0, 0],
      winText: 'The hollow has been filled with love.',
      loseText: 'The hollow still echoes.',
    },
    {
      selectText: `Sensualist`,
      missionText: `With my companion by my side, I can see clearly even in the darkest nights. Together we navigate the shadows, finding our way when others would be lost.`,
      uponRoundWinText: [
        `My night vision is clear.`,
        `I see through the darkness.`,
        `We navigate together.`,
        `The shadows hold no fear.`,
        `I am the night hunter.`,
        `I am the cat with night vision.`,
      ],
      deck: [...x('Stars', 2), ...x('Rose', 2), ...x('Sensualist', 3)],
      opponentDeck: [21, 20, 20, 17, 14, 14, 14, 6, 3, 3, 3, 3, 0, 0, 0],
      winText: 'Night vision has guided us to victory.',
      loseText: 'The night vision still guides us.',
    },
    {
      selectText: `Finale - bounty?`,
      missionText: `Like a sunflower turning toward the light, my companion and I turn toward each other. We grow together, always seeking the warmth and light of our bond.`,
      uponRoundWinText: [
        `We turn toward the light.`,
        `The sunflower blooms.`,
        `We grow toward each other.`,
        `The light guides us.`,
        `We are the sunflowers.`,
        `I am the sunflower with my pet.`,
      ],
      deck: [...x('Stars', 2), ...x('Rose', 2)],
      opponentDeck: [21, 20, 20, 17, 14, 14, 14, 6, 3, 3, 3, 3, 0, 0, 0],
      winText: 'The sunflowers have bloomed together.',
      loseText: 'The sunflowers still turn toward the light.',
    },
    // More levels
  ],
  // Imani
  [
    {
      selectText: `I am a doula`,
      missionText: `I am a doula and this is my mission`,
      uponRoundWinText: [
        `0 I am afraid of the doula`,
        `1 I am not afraid of the doula`,
        `2 I am not afraid of the doula`,
        `3 I am not afraid of the doula`,
        `4 I am not afraid of the doula`,
        `5 I am not afraid of the doula`,
      ],
      deck: [
        ...x('Nascence', 4),
        ...x('Hug', 2),
        ...x('Fruit', 2),
        ...x('Hurricane', 1),
        ...x('Uprising', 1),
      ],
      opponentDeck: [18, 18, 51, 51, 15, 15, 48, 48, 48, 7, 7, 33, 33, 4, 4],
      winText: 'I have won and I am a doula.',
      loseText: 'I lost and I am a doula.',
    },
    {
      selectText: `Birth 1 - BIRTH`,
      missionText: `Every birth begins with nascence, the first stirrings of new life. As a doula, I witness the miracle of creation, the moment when potential becomes reality. I guide the journey from possibility to existence.`,
      uponRoundWinText: [
        `The first stirrings begin.`,
        `New life is emerging.`,
        `I guide the process.`,
        `The miracle unfolds.`,
        `Potential becomes reality.`,
        `I am the witness to nascence.`,
      ],
      deck: [
        ...x('Nascence', 2),
        ...x('Dagger', 2),
        ...x('Birth', 2),
        ...x('Hug', 1),
      ],
      opponentDeck: [21, 17, 17, 14, 14, 14, 12, 12, 6, 3, 3, 3, 3, 3, 0],
      winText: 'New life has been brought into the world.',
      loseText: 'The journey of birth continues.',
    },
    {
      selectText: `Birth 2 - The Future`,
      missionText: `Posterity is the legacy we leave behind, the future generations that will carry our stories forward. As a doula, I help create the foundation for what will come, ensuring that each birth contributes to the ongoing story of humanity.`,
      uponRoundWinText: [
        `The legacy takes shape.`,
        `Future generations await.`,
        `I build the foundation.`,
        `The story continues.`,
        `Posterity is secured.`,
        `I am the guardian of posterity.`,
      ],
      deck: [...x('Nascence', 2), ...x('Birth', 2), ...x('The Future', 2)],
      opponentDeck: [0, 3, 3, 3, 3, 6, 74, 74, 12, 14, 14, 14, 51, 46, 46],
      winText: 'The legacy of posterity is preserved.',
      loseText: 'The future still awaits.',
    },
    {
      selectText: `Birth 3 - Posterity`,
      missionText: `Birth itself is the sacred moment when the impossible becomes possible. I am there to support, to guide, to witness the transformation from darkness to light, from potential to actuality. Every birth is a miracle.`,
      uponRoundWinText: [
        `The sacred moment arrives.`,
        `I support the transformation.`,
        `Darkness becomes light.`,
        `The miracle unfolds.`,
        `Birth is complete.`,
        `I am the witness to miracles.`,
      ],
      deck: [...x('Dove', 3), ...x('Starling', 2), ...x('Posterity', 2)],
      opponentDeck: [63, 63, 63, 63, 7, 7, 7, 11, 12, 40, 40, 51, 51, 21, 56],
      winText: 'The miracle of birth is complete.',
      loseText: 'The miracle still awaits.',
    },
    {
      selectText: `Birth 4 - Ancestry`,
      missionText: `The cradle holds the promise of the future, a safe space where new life can grow and flourish. As a doula, I help create this sanctuary, ensuring that every child has the foundation they need to thrive.`,
      uponRoundWinText: [
        `The cradle provides safety.`,
        `New life grows strong.`,
        `I create the sanctuary.`,
        `The foundation is secure.`,
        `The future is protected.`,
        `I am the guardian of the cradle.`,
      ],
      deck: [
        ...x('Nascence', 2),
        ...x('Rose', 2),
        ...x('Hold Tight', 1),
        ...x('Ancestry', 1),
        ...x('The Future', 1),
      ],
      opponentDeck: [25, 25, 25, 6, 31, 7, 39, 39, 39, 15, 40, 67, 67, 57, 45],
      winText: 'The cradle has nurtured new life.',
      loseText: 'The cradle still provides protection.',
    },
    {
      selectText: `Birth 5 - Pregnant`,
      missionText: `The future is built on every birth, every child, every new beginning. As a doula, I am part of creating that future, helping to bring forth the next generation that will shape the world to come.`,
      uponRoundWinText: [
        `The future takes shape.`,
        `I help build tomorrow.`,
        `New generations emerge.`,
        `The world transforms.`,
        `The future is bright.`,
        `I am the architect of the future.`,
      ],
      deck: [
        ...x('Nascence', 2),
        ...x('Pregnant', 1),
        ...x('Birth', 2),
        ...x('Hungry Ghost', 1),
        ...x('Hurricane', 1),
        ...x('Oak', 1),
      ],
      opponentDeck: [63, 25, 25, 7, 69, 69, 39, 39, 48, 11, 13, 13, 57, 57, 23],
      winText: 'The future has been secured.',
      loseText: 'The future still beckons.',
    },
    {
      selectText: `Birth 6 - Cradle`,
      missionText: `Every birth connects us to our ancestry, to the long line of mothers and fathers who came before. As a doula, I honor this connection, understanding that each birth is part of a greater story that stretches back through time.`,
      uponRoundWinText: [
        `I honor my ancestry.`,
        `The line continues.`,
        `I am part of the story.`,
        `The connection is strong.`,
        `Ancestry guides me.`,
        `I am the keeper of ancestry.`,
      ],
      deck: [
        ...x('Stars', 2),
        ...x('Rose', 2),
        ...x('Cradle', 2),
        ...x('Boa', 1),
      ],
      opponentDeck: [0, 4, 28, 28, 28, 33, 33, 33, 34, 34, 11, 11, 11, 11, 71],
      winText: 'The ancestry has been honored.',
      loseText: 'The ancestral line continues.',
    },
    {
      selectText: `Bonus: Rebirth`,
      missionText: `Sometimes birth is not just about new life, but about rebirth - the transformation of what already exists into something new and beautiful. As a doula, I witness these transformations, helping to guide the process of becoming.`,
      uponRoundWinText: [
        `The transformation begins.`,
        `I guide the rebirth.`,
        `Old becomes new.`,
        `The process unfolds.`,
        `Rebirth is complete.`,
        `I am the witness to rebirth.`,
      ],
      deck: [...x('Dove', 5), ...x('Starling', 3), ...x('Pass On', 1)],
      opponentDeck: [63, 25, 25, 7, 69, 69, 39, 39, 48, 11, 13, 13, 57, 57, 23],
      winText: 'The rebirth has been completed.',
      loseText: 'The transformation continues.',
    },
    // More levels
  ],
  // Mitra
  [
    {
      selectText: `I am a seeker`,
      missionText: `I am a seeker and this is my mission`,
      uponRoundWinText: [
        `0 I am afraid of the seeker`,
        `1 I am not afraid of the seeker`,
        `2 I am not afraid of the seeker`,
        `3 I am not afraid of the seeker`,
        `4 I am not afraid of the seeker`,
        `5 I am not afraid of the seeker`,
      ],
      deck: [50, 27, 27, 27, 27],
      opponentDeck: [],
      winText: 'I have won and I am a seeker.',
      loseText: 'I lost and I am a seeker.',
    },
    {
      selectText: `Vision 1 - Clear View`,
      missionText: `As a seeker, I must have clear vision to find what I'm looking for. The path ahead must be unobstructed, the truth must be visible. I seek clarity in a world of confusion and doubt.`,
      uponRoundWinText: [
        `My vision becomes clear.`,
        `I see the path ahead.`,
        `The truth is revealed.`,
        `Clarity guides me.`,
        `I have clear sight.`,
        `I am the seeker with clear view.`,
      ],
      deck: [27, 27, 27, 27, 12, 12, 12, 13],
      opponentDeck: [2, 2, 2, 2, 4, 4, 8, 8, 8, 10, 60, 11, 15, 22, 22],
      winText: 'Clear vision has guided me to truth.',
      loseText: 'The path to clarity continues.',
    },
    {
      selectText: `Vision 2 - Enlightenment`,
      missionText: `Enlightenment is the moment when understanding dawns, when the pieces of the puzzle fall into place. As a seeker, I pursue this moment of revelation, when knowledge becomes wisdom.`,
      uponRoundWinText: [
        `Understanding dawns.`,
        `The pieces fall into place.`,
        `Enlightenment arrives.`,
        `Knowledge becomes wisdom.`,
        `The revelation is complete.`,
        `I am the enlightened seeker.`,
      ],
      deck: [27, 27, 45, 45],
      opponentDeck: [2, 0, 5, 3, 3, 3, 8, 8, 60, 60, 14, 17, 17, 20, 21],
      winText: 'Enlightenment has been achieved.',
      loseText: 'The path to enlightenment continues.',
    },
    {
      selectText: `Vision 3 - Awakening`,
      missionText: `Awakening is the moment when consciousness expands, when we see beyond the surface of things. As a seeker, I experience this awakening, becoming aware of deeper truths and hidden realities.`,
      uponRoundWinText: [
        `Consciousness expands.`,
        `I see beyond the surface.`,
        `The awakening begins.`,
        `Deeper truths emerge.`,
        `Hidden realities are revealed.`,
        `I am the awakened seeker.`,
      ],
      deck: [1, 1, 1, 39, 39, 39],
      opponentDeck: [0, 0, 3, 3, 3, 3, 28, 28, 33, 33, 34, 11, 11, 11, 71],
      winText: 'The awakening is complete.',
      loseText: 'The awakening continues.',
    },
    {
      selectText: `Vision 4 - Nectar`,
      missionText: `Nectar is the sweet essence of truth, the reward for the seeker's journey. It is the knowledge that nourishes the soul, the understanding that sustains the spirit. I seek this nectar of wisdom.`,
      uponRoundWinText: [
        `The nectar flows.`,
        `I taste the sweet truth.`,
        `Wisdom nourishes me.`,
        `The essence is revealed.`,
        `My soul is sustained.`,
        `I am the seeker of nectar.`,
      ],
      deck: [25, 25, 33, 34],
      opponentDeck: [63, 63, 5, 5, 3, 6, 6, 12, 12, 14, 14, 17, 17, 20, 56],
      winText: 'The nectar of wisdom is mine.',
      loseText: 'The nectar still flows.',
    },
    {
      selectText: `Vision 5 - Conquer`,
      missionText: `To conquer is to master the challenges of the seeker's path, to overcome the obstacles that stand between me and truth. I conquer not through force, but through understanding and perseverance.`,
      uponRoundWinText: [
        `I master the challenges.`,
        `Obstacles fall away.`,
        `Understanding conquers all.`,
        `The path is cleared.`,
        `Victory through wisdom.`,
        `I am the conquering seeker.`,
      ],
      deck: [12, 67, 67, 67, 18],
      opponentDeck: [0, 0, 26, 26, 26, 26, 6, 33, 33, 33, 12, 15, 40, 40, 46],
      winText: 'I have conquered through wisdom.',
      loseText: 'The conquest continues.',
    },
    {
      selectText: `Vision Alt 1 - Prey`,
      missionText: `Sometimes the seeker becomes the prey, hunted by the very truths they pursue. But in being hunted, I learn to move differently, to see the world from a new perspective. The prey teaches the hunter.`,
      uponRoundWinText: [
        `I become the prey.`,
        `I learn to move differently.`,
        `New perspectives emerge.`,
        `The hunted becomes wise.`,
        `I understand the hunt.`,
        `I am the wise prey.`,
      ],
      deck: [27, 27, 26, 26, 7, 12, 15],
      opponentDeck: [2, 2, 1, 1, 63, 63, 8, 8, 6, 60, 60, 40, 40, 51, 46],
      winText: 'The prey has become the teacher.',
      loseText: 'The hunt continues.',
    },
    {
      selectText: `Vision Alt 2 - Dawn`,
      missionText: `Dawn is the moment when light breaks through darkness, when new possibilities emerge. As a seeker, I witness this dawn, understanding that every ending is also a beginning, every darkness gives way to light.`,
      uponRoundWinText: [
        `Light breaks through darkness.`,
        `New possibilities emerge.`,
        `The dawn arrives.`,
        `Every ending is a beginning.`,
        `Darkness gives way to light.`,
        `I am the seeker of dawn.`,
      ],
      deck: [50, 4, 4, 7, 7],
      opponentDeck: [2, 63, 3, 3, 8, 8, 8, 31, 48, 48, 60, 15, 18, 22, 22],
      winText: 'The dawn has brought new understanding.',
      loseText: 'The dawn still approaches.',
    },
    // More levels
  ],
]
