// This file is auto-generated. Do not edit manually.
export const assetLists = {
  "avatar": {
    "files": [
      "Adonis",
      "Imani",
      "Jules",
      "Kitz",
      "Mia",
      "Mitra",
      "AdonisFull",
      "ImaniFull",
      "JulesFull",
      "KitzFull",
      "MiaFull",
      "MitraFull"
    ],
    "dimensions": {
      "Adonis": {
        "width": 130,
        "height": 130
      },
      "Imani": {
        "width": 130,
        "height": 130
      },
      "Jules": {
        "width": 130,
        "height": 130
      },
      "Kitz": {
        "width": 130,
        "height": 130
      },
      "Mia": {
        "width": 130,
        "height": 130
      },
      "Mitra": {
        "width": 130,
        "height": 130
      }
    },
    "pixelArt": true
  },
  "card": {
    "files": [
      "Abundance",
      "Ancestry",
      "Arsonist",
      "Ashes",
      "Awakening",
      "Balance",
      "Begging Bowl",
      "Birth",
      "Boa",
      "Bounty",
      "Bull",
      "Cardback",
      "Celebration",
      "Child",
      "Clear View",
      "Cling",
      "Cloak of Stars",
      "Cloud",
      "Conquer",
      "Cosmos",
      "Cradle",
      "Dagger",
      "Dam Breaks",
      "Dash",
      "Dawn",
      "Death",
      "Default",
      "Defiance",
      "Dew",
      "Dove",
      "Dreamer",
      "Drown",
      "Ecology",
      "Enlightenment",
      "Excess",
      "Fates",
      "Firebug",
      "Fish",
      "Fishing Boat",
      "Fledgling",
      "From Ashes",
      "Fruit",
      "Gain and Loss",
      "Gentle Rain",
      "Goliath",
      "Heirloom",
      "Hero",
      "Heron",
      "Hold Tight",
      "Hollow",
      "Hug",
      "Hungry Ghost",
      "Hurricane",
      "Iceberg",
      "Immolant",
      "Imprison",
      "Impulse",
      "Just Like Dad",
      "Lantern",
      "Lay Bare",
      "Let Go",
      "Lost in Shadow",
      "Me and Her",
      "Mercy",
      "Mine",
      "Moon",
      "Nascence",
      "Nectar",
      "Nest",
      "Night Vision",
      "Nightmare",
      "Oak",
      "Overflow",
      "Parade",
      "Paramountcy",
      "Parch",
      "Pass On",
      "Pet",
      "Phoenix",
      "Pomegranate",
      "Possibility",
      "Posterity",
      "Predator",
      "Pregnant",
      "Prey",
      "Pride",
      "Rebirth",
      "Refresh",
      "Riddle",
      "Rooster",
      "Rose",
      "Secretary Bird",
      "Seen",
      "Sensualist",
      "Shadow",
      "Sickness",
      "Spark",
      "Starling",
      "Stars",
      "Storytime",
      "Sun",
      "Sunflower",
      "Supernova",
      "The Future",
      "Timid",
      "Truth",
      "Uprising",
      "Vampire",
      "Veteran",
      "Victim",
      "Vulture",
      "Wing Clipping",
      "Yearn"
    ],
    "pixelArt": true
  },
  "cutout": {
    "files": [
      "Abundance",
      "Ancestry",
      "Arsonist",
      "Awakening",
      "Balance",
      "Begging Bowl",
      "Birth",
      "Boa",
      "Bounty",
      "Bull",
      "Clear View",
      "Cling",
      "Cloak of Stars",
      "Cloud",
      "Conquer",
      "Cosmos",
      "Cradle",
      "Dagger",
      "Dam Breaks",
      "Dash",
      "Dawn",
      "Death",
      "Defiance",
      "Dew",
      "Dove",
      "Dreamer",
      "Drown",
      "Ecology",
      "Enlightenment",
      "Excess",
      "Fates",
      "Firebug",
      "Fish",
      "Fishing Boat",
      "Fledgling",
      "From Ashes",
      "Fruit",
      "Gain and Loss",
      "Gentle Rain",
      "Goliath",
      "Hero",
      "Heron",
      "Hold Tight",
      "Hollow",
      "Hug",
      "Hungry Ghost",
      "Hurricane",
      "Iceberg",
      "Immolant",
      "Imprison",
      "Impulse",
      "Just Like Dad",
      "Lantern",
      "Lay Bare",
      "Let Go",
      "Lost in Shadow",
      "Me and Her",
      "Mercy",
      "Mine",
      "Moon",
      "Nascence",
      "Nectar",
      "Nest",
      "Night Vision",
      "Nightmare",
      "Oak",
      "Overflow",
      "Parade",
      "Paramountcy",
      "Parch",
      "Pass On",
      "Pet",
      "Phoenix",
      "Pomegranate",
      "Possibility",
      "Posterity",
      "Pregnant",
      "Prey",
      "Pride",
      "Rebirth",
      "Refresh",
      "Riddle",
      "Rooster",
      "Rose",
      "Secretary Bird",
      "Sensualist",
      "Shadow",
      "Sickness",
      "Spark",
      "Starling",
      "Stars",
      "Storytime",
      "Sun",
      "Sunflower",
      "The Future",
      "Timid",
      "Truth",
      "Uprising",
      "Vampire",
      "Veteran",
      "Victim",
      "Vulture",
      "Wing Clipping",
      "Yearn"
    ],
    "pixelArt": true
  },
  "icon": {
    "files": [
      "Mission",
      "Arrow",
      "Border",
      "BreathBasic",
      "BreathExtra",
      "BreathHover",
      "BreathOom",
      "BreathSpent",
      "CustomDeck",
      "Deck",
      "DeckbuilderTab",
      "Discard",
      "Discord",
      "Edit",
      "Friends",
      "History",
      "HomeButton",
      "InputText",
      "Inspire",
      "JourneyTab",
      "Leaderboard",
      "LeaderboardTab",
      "MatchHistoryTab",
      "Moon",
      "Network",
      "New",
      "Nourish",
      "Options",
      "PlayTab",
      "PlayTab",
      "Pointer",
      "ProfileTab",
      "ProfileTab",
      "Quest",
      "QuestionMark",
      "QuestsTab",
      "Recap",
      "Search",
      "Share",
      "Sight",
      "Skip",
      "SmallX",
      "Speed",
      "Status",
      "Store",
      "StoreTab",
      "Sun",
      "Thumb",
      "Underline",
      "Wins",
      "XOut"
    ],
    "dimensions": {
      "Mission": {
        "width": 80,
        "height": 80
      }
    },
    "pixelArt": false
  },
  "store": {
    "files": [
      "Butterfly-full",
      "Butterfly",
      "DandelionRelic-full",
      "DandelionRelic",
      "Imani-full",
      "Imani",
      "JadeCardback-full",
      "JadeCardback",
      "Jules-full",
      "Jules",
      "ThornBorder-full",
      "ThornBorder"
    ],
    "pixelArt": true
  },
  "background": {
    "files": [
      "Dark",
      "Light"
    ],
    "pixelArt": false
  },
  "journey": {
    "files": [
      "Map",
      "Match",
      "Mission",
      "Story 1",
      "Story 2",
      "Story 3",
      "Story 4"
    ],
    "pixelArt": true
  },
  "border": {
    "files": [
      "Ashes",
      "Birds",
      "Birth",
      "Grape",
      "None",
      "Shadow",
      "Stars",
      "Thorns",
      "Vision",
      "Water"
    ],
    "pixelArt": true
  },
  "relic": {
    "files": [
      "Dandelion"
    ],
    "dimensions": {
      "Dandelion": {
        "width": 80,
        "height": 160
      }
    },
    "pixelArt": true
  },
  "pet": {
    "files": [
      "Butterfly"
    ],
    "pixelArt": false
  },
  "roundResult": {
    "files": [
      "Lose",
      "Tie",
      "Win"
    ],
    "dimensions": {
      "Lose": {
        "width": 563,
        "height": 258
      },
      "Tie": {
        "width": 563,
        "height": 258
      },
      "Win": {
        "width": 563,
        "height": 258
      }
    },
    "pixelArt": false
  },
  "chrome": {
    "files": [
      "Avatar",
      "CloudBottom",
      "CloudTop",
      "Hand",
      "ResultGlow"
    ],
    "pixelArt": false
  },
  "news": {
    "files": [
      "Birth",
      "Goliath",
      "LayBare",
      "MeAndHer",
      "Nightmare",
      "Possibilities",
      "Refresh"
    ],
    "pixelArt": true
  },
  "sfx": {
    "files": [
      "click",
      "close 1",
      "close 2",
      "create 1",
      "create 2",
      "create 3",
      "discard 1",
      "discard 2",
      "discard 3",
      "draw",
      "failure",
      "inspire",
      "lose",
      "match found",
      "nourish",
      "open 1",
      "open 2",
      "pass",
      "play 1",
      "play 2",
      "play 3",
      "play 4",
      "play them 1",
      "play them 2",
      "play them 3",
      "play them 4",
      "resolve 1",
      "resolve 2",
      "resolve 3",
      "resolve 4",
      "resolve 5",
      "shuffle",
      "tie",
      "win"
    ]
  },
  "dialog": {
    "files": [
      "Adonis",
      "Imani",
      "Jules",
      "Kitz",
      "Mia",
      "Mitra"
    ]
  }
} as const;