// This file is auto-generated. Do not edit manually.
export const assetLists = {
  "avatar": {
    "files": [
      "umbra1",
      "umbra2",
      "Adonis",
      "Jules",
      "Kitz",
      "Mia",
      "Mitra",
      "Renata",
      "AdonisFull",
      "JulesFull",
      "KitzFull",
      "MiaFull",
      "MitraFull",
      "RenataFull"
    ],
    "dimensions": {
      "umbra1": {
        "width": 128,
        "height": 128
      },
      "umbra2": {
        "width": 128,
        "height": 128
      },
      "Adonis": {
        "width": 130,
        "height": 130
      },
      "Jules": {
        "width": 130,
        "height": 130
      },
      "Kitz": {
        "width": 130,
        "height": 130
      },
      "Mia": {
        "width": 130,
        "height": 130
      },
      "Mitra": {
        "width": 130,
        "height": 130
      },
      "Renata": {
        "width": 130,
        "height": 130
      }
    },
    "pixelArt": false
  },
  "cardback": {
    "files": [
      "Astrology",
      "Blossom",
      "Default",
      "Hill",
      "Lotus"
    ],
    "pixelArt": false
  },
  "card": {
    "files": [],
    "pixelArt": true
  },
  "card/background": {
    "files": [
      "0",
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8"
    ],
    "pixelArt": false
  },
  "card/subject": {
    "files": [
      "Abandoned",
      "Abundance",
      "Ancestry",
      "Arsonist",
      "Ashes",
      "Awakening",
      "Balance",
      "Begging Bowl",
      "Beginner's Mind",
      "Birdsong",
      "Birth",
      "Boa",
      "Bounty",
      "Bull",
      "Child",
      "Clear View",
      "Cling",
      "Cloak of Stars",
      "Cloud",
      "Conquer",
      "Cosmos",
      "Cradle",
      "Dagger",
      "Dam Breaks",
      "Dash",
      "Dawn",
      "Death",
      "Defiance",
      "Dew",
      "Doll",
      "Dove",
      "Dreamer",
      "Drown",
      "Ecology",
      "Enlightenment",
      "Enlightment",
      "Excess",
      "Fates",
      "Firebug",
      "Fish",
      "Fishing Boat",
      "Fledgling",
      "From Ashes",
      "Fruit",
      "Gain and Loss",
      "Gentle Rain",
      "Goliath",
      "Heart",
      "Heirloom",
      "Hero",
      "Heron",
      "Hold Tight",
      "Hollow",
      "Hug",
      "Hungry Ghost",
      "Hurricane",
      "Ice",
      "Iceberg",
      "Immolant",
      "Imprison",
      "Impulse",
      "Isolation",
      "Just Like Dad",
      "Lantern",
      "Lay Bare",
      "Let Go",
      "Liquidity",
      "Lost in Shadow",
      "Me and Her",
      "Mercy",
      "Mine",
      "Moloch",
      "Moon",
      "Nascence",
      "Nectar",
      "Nest",
      "Night Vision",
      "Nightmare",
      "Oak",
      "Overflow",
      "Parade",
      "Paramountcy",
      "Parch",
      "Pass On",
      "Pet",
      "Phoenix",
      "Pomegranate",
      "Possibility",
      "Posterity",
      "Predator",
      "Pregnant",
      "Prey",
      "Pride",
      "Rebirth",
      "Refresh",
      "Riddle",
      "Rooster",
      "Rose",
      "Secretary Bird",
      "Seen",
      "Sensualist",
      "Shadow",
      "Sickness",
      "Sky Burial",
      "Spark",
      "Starfall",
      "Starling",
      "Stars",
      "Storytime",
      "Sudden Insight",
      "Sun",
      "Sunflower",
      "The Future",
      "Timid",
      "Truth",
      "Uprising",
      "Vampire",
      "Veteran",
      "Victim",
      "Voices",
      "Vulture",
      "Wing Clipping",
      "Yearn"
    ],
    "pixelArt": false
  },
  "card/arc": {
    "files": [
      "0",
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8"
    ],
    "pixelArt": false
  },
  "card/container": {
    "files": [
      "0",
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8"
    ],
    "pixelArt": false
  },
  "card/effects": {
    "files": [
      "shadow"
    ],
    "pixelArt": false
  },
  "cutout": {
    "files": [
      "Abandoned",
      "Abundance",
      "Ancestry",
      "Arsonist",
      "Awakening",
      "Balance",
      "Begging Bowl",
      "Beginner's Mind",
      "Birdsong",
      "Birth",
      "Boa",
      "Bounty",
      "Bull",
      "Clear View",
      "Cling",
      "Cloak of Stars",
      "Cloud",
      "Conquer",
      "Cosmos",
      "Cradle",
      "Dagger",
      "Dam Breaks",
      "Dash",
      "Dawn",
      "Death",
      "Default",
      "Defiance",
      "Dew",
      "Doll",
      "Dove",
      "Dreamer",
      "Drown",
      "Ecology",
      "Enlightenment",
      "Excess",
      "Fates",
      "Firebug",
      "Fish",
      "Fishing Boat",
      "Fledgling",
      "From Ashes",
      "Fruit",
      "Gain and Loss",
      "Gentle Rain",
      "Goliath",
      "Heart",
      "Hero",
      "Heron",
      "Hold Tight",
      "Hollow",
      "Hug",
      "Hungry Ghost",
      "Hurricane",
      "Iceberg",
      "Immolant",
      "Imprison",
      "Impulse",
      "Isolation",
      "Just Like Dad",
      "Lantern",
      "Lay Bare",
      "Let Go",
      "Liquidity",
      "Lost in Shadow",
      "Me and Her",
      "Mercy",
      "Mine",
      "Moloch",
      "Moon",
      "Nascence",
      "Nectar",
      "Nest",
      "Night Vision",
      "Nightmare",
      "Oak",
      "Overflow",
      "Parade",
      "Paramountcy",
      "Parch",
      "Pass On",
      "Pet",
      "Phoenix",
      "Pomegranate",
      "Possibility",
      "Posterity",
      "Pregnant",
      "Prey",
      "Pride",
      "Rebirth",
      "Refresh",
      "Riddle",
      "Rooster",
      "Rose",
      "Secretary Bird",
      "Sensualist",
      "Shadow",
      "Sickness",
      "Sky Burial",
      "Spark",
      "Starfall",
      "Starling",
      "Stars",
      "Storytime",
      "Sudden Insight",
      "Sun",
      "Sunflower",
      "The Future",
      "Timid",
      "Truth",
      "Uprising",
      "Vampire",
      "Veteran",
      "Victim",
      "Voices",
      "Vulture",
      "Wing Clipping",
      "Yearn"
    ],
    "pixelArt": true
  },
  "icon": {
    "files": [
      "Wins",
      "BreathBasic",
      "BreathExtra",
      "BreathHover",
      "BreathOom",
      "BreathSpent",
      "BreathUnavailable",
      "DeckbuilderTab",
      "Discord",
      "InputText",
      "Inspire",
      "JourneyStar",
      "JourneyTab",
      "LeaderboardTab",
      "Left",
      "MatchHistoryTab",
      "Moon",
      "Moon",
      "Network",
      "Nourish",
      "Options",
      "PlayButton",
      "PlayTab",
      "ProfileTab",
      "QuestsTab",
      "Recap",
      "Right",
      "Share",
      "Sight",
      "SmallX",
      "Social",
      "Status",
      "StoreTab",
      "Sun",
      "ThumbHorizontal",
      "ThumbTall",
      "TrackHorizontal",
      "Underline",
      "XOut",
      "cardIcon",
      "coin",
      "gem",
      "scroll",
      "scrollDark"
    ],
    "dimensions": {
      "Wins": {
        "width": 157,
        "height": 1080
      }
    },
    "pixelArt": false
  },
  "background": {
    "files": [
      "Light",
      "intro",
      "matchBottom",
      "matchDay",
      "matchNight",
      "matchTile",
      "matchTop"
    ],
    "pixelArt": false
  },
  "border": {
    "files": [
      "Ashes",
      "Birds",
      "Birth",
      "Grape",
      "None",
      "Shadow",
      "Stars",
      "Thorns",
      "Vision",
      "Water"
    ],
    "pixelArt": true
  },
  "relic": {
    "files": [
      "Dandelion"
    ],
    "dimensions": {
      "Dandelion": {
        "width": 80,
        "height": 160
      }
    },
    "pixelArt": true
  },
  "roundResult/Win": {
    "files": [
      "backdrop",
      "sun",
      "sunbeam1",
      "sunbeam2",
      "sunbeam3",
      "sunbeam4",
      "text",
      "umbra"
    ],
    "pixelArt": false
  },
  "roundResult/Loss": {
    "files": [
      "backdrop",
      "cloud1",
      "cloud2",
      "cloud3",
      "puddles",
      "rainBack",
      "rainClose",
      "rainMid",
      "text",
      "umbra"
    ],
    "pixelArt": false
  },
  "roundResult/Tie": {
    "files": [
      "backdrop",
      "gustBack",
      "gustClose",
      "gustMid",
      "leaves1",
      "leaves2",
      "leaves3",
      "leaves4",
      "leaves5",
      "text",
      "umbras"
    ],
    "pixelArt": false
  },
  "chrome": {
    "files": [
      "CloudBottom",
      "CloudTop",
      "Recap",
      "body",
      "bodyAlt",
      "breathWheel",
      "bubble",
      "bubbleEffect",
      "bubbleNourish",
      "builderDecklist",
      "builderHeader",
      "builderLeftCorner",
      "builderRightCorner",
      "builderVertical",
      "corner",
      "divider",
      "editorScroll",
      "editorScrollBottom",
      "editorTopCorner",
      "error",
      "header",
      "introBox",
      "introLeft",
      "introRight",
      "journeyHeader",
      "nameplate",
      "profile",
      "stackCount",
      "sundial",
      "tabSelector",
      "thumbnailNameplate"
    ],
    "pixelArt": false
  },
  "news": {
    "files": []
  },
  "sfx": {
    "files": [
      "click",
      "close 1",
      "close 2",
      "create 1",
      "create 2",
      "create 3",
      "discard 1",
      "discard 2",
      "discard 3",
      "draw",
      "failure",
      "inspire",
      "lose",
      "match found",
      "nourish",
      "open 1",
      "open 2",
      "pass",
      "play 1",
      "play 2",
      "play 3",
      "play 4",
      "play them 1",
      "play them 2",
      "play them 3",
      "play them 4",
      "resolve 1",
      "resolve 2",
      "resolve 3",
      "resolve 4",
      "resolve 5",
      "shuffle",
      "tie",
      "win"
    ]
  },
  "dialog": {
    "files": []
  },
  "tutorial": {
    "files": [
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9"
    ],
    "pixelArt": false
  }
} as const;