// Copies the game's card assets and exports card/keyword data into the card
// maker, so its cards always match the game's. Runs at Docker image build
// (see Dockerfile) and locally after game assets or card data change:
//
//   npx -y tsx sites/cardmaker/generateAssets.ts
//
// Everything it writes under assets/ is generated — gitignored, never edited.

import * as fs from 'fs'
import * as path from 'path'
import { fileURLToPath } from 'url'
import { Keywords } from '../../shared/state/keyword'
import Catalog from '../../shared/state/catalog'

const here = path.dirname(fileURLToPath(import.meta.url))
const repoRoot = path.resolve(here, '../..')
const gameCardAssets = path.join(repoRoot, 'client/assets/img/card')
const outDir = path.join(here, 'assets')

// --- Frame layers (background / arc / container, one per theme) ---
for (const kind of ['background', 'arc', 'container']) {
  const dest = path.join(outDir, 'card', kind)
  fs.rmSync(dest, { recursive: true, force: true })
  fs.cpSync(path.join(gameCardAssets, kind), dest, { recursive: true })
}

// --- Subject arts ---
const subjectsDest = path.join(outDir, 'subjects')
fs.rmSync(subjectsDest, { recursive: true, force: true })
fs.cpSync(path.join(gameCardAssets, 'subject'), subjectsDest, {
  recursive: true,
})

// --- Card / keyword data ---
const keywords = Keywords.getAll().map((k) => ({
  name: k.name,
  text: k.text,
  hasX: !!k.hasX,
}))
// Collectible cards plus tokens (Ashes, Child, …) — the game's own
// card-reference matching runs over allCards, so tokens belong here too
const collectibleIds = new Set(
  Catalog.collectibleCardsWithBetaCards.map((c) => c.id),
)
const cardData = (c: any, token: boolean) => ({
  name: c.name,
  cost: c.cost,
  points: c.points,
  text: c.text,
  theme: c.theme ?? 0,
  ...(token ? { token: true } : {}),
})
// Tokens with an id above this are excluded from the card maker
const MAX_TOKEN_ID = 2000
const cards = [
  ...Catalog.collectibleCards.map((c) => cardData(c, false)),
  ...Catalog.allCards
    .filter((c) => !collectibleIds.has(c.id) && c.id <= MAX_TOKEN_ID)
    .map((c) => cardData(c, true)),
]
const subjects = fs
  .readdirSync(subjectsDest)
  .filter((f) => f.endsWith('.webp'))
  .map((f) => f.replace('.webp', ''))
  .sort()

fs.writeFileSync(
  path.join(outDir, 'gameData.json'),
  JSON.stringify({ keywords, cards, subjects }, null, 2),
)

// --- Per-card pages: /cardmaker/{slug}/ ---
// Every directory under cardmaker/ except these is a generated card page
// (the root .gitignore encodes the same contract).
const KEEP_DIRS = new Set(['assets', 'search', 'community'])
const GENERATED_MARKER = '<!-- generated by generateAssets.ts -->'

// Must match slugify in search/search.js
const slugify = (name: string) =>
  name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')

const escapeHtml = (s: string) =>
  s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')

// Remove stale card pages from a previous run (only dirs we marked)
for (const entry of fs.readdirSync(here, { withFileTypes: true })) {
  if (!entry.isDirectory() || KEEP_DIRS.has(entry.name)) continue
  const index = path.join(here, entry.name, 'index.html')
  if (
    fs.existsSync(index) &&
    fs.readFileSync(index, 'utf8').includes(GENERATED_MARKER)
  ) {
    fs.rmSync(path.join(here, entry.name), { recursive: true })
  }
}

const seenSlugs = new Map<string, string>()
for (const card of cards) {
  const slug = slugify(card.name)
  if (seenSlugs.has(slug)) {
    throw new Error(
      `Slug collision: "${card.name}" and "${seenSlugs.get(slug)}" both map to /${slug}/`,
    )
  }
  seenSlugs.set(slug, card.name)

  const description = escapeHtml(
    `${card.name} — ${card.token ? 'token, ' : ''}${card.cost} cost, ${card.points} point${card.points === 1 ? '' : 's'}. ${card.text.replace(/\n/g, ' ')}`,
  )

  const html = `<!doctype html>
${GENERATED_MARKER}
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${escapeHtml(card.name)} — Celestial</title>
    <meta name="description" content="${description}" />
    <link rel="icon" type="image/svg+xml" href="../../about/assets/favicon.svg" />
    <link rel="stylesheet" href="../cardmaker.css" />
  </head>
  <body>
    <header class="site-header">
      <h1>${escapeHtml(card.name)}</h1>
      <nav class="page-nav">
        <a href="../">Card Maker</a>
        <a href="../search/">Card Search</a>
        <a href="https://celestialdecks.gg">Play the Game</a>
      </nav>
    </header>

    <main class="card-page">
      <div class="card-column">
        <div id="card-mount"></div>
        <div class="card-actions">
          <button id="btn-download" type="button">Download</button>
        </div>
        <div id="reminders" class="reminders" hidden></div>
      </div>
      <div id="ref-cards" class="ref-cards" hidden></div>
    </main>

    <footer class="site-footer">
      <p>
        <a href="https://celestialdecks.gg">Play Celestial</a> ·
        <a href="https://discord.gg/UXWswspB8S">Discord</a>
      </p>
    </footer>

    <script type="application/json" id="card-data">${JSON.stringify(card).replace(/</g, '\\u003c')}</script>
    <script type="module" src="../cardPage.js"></script>
  </body>
</html>
`
  const dir = path.join(here, slug)
  fs.mkdirSync(dir, { recursive: true })
  fs.writeFileSync(path.join(dir, 'index.html'), html)
}

console.log(
  `cardmaker assets generated: ${keywords.length} keywords, ${cards.length} cards (+pages), ${subjects.length} subjects`,
)
